name: Generate Sponsors
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - package.json
      - package-lock.json
      - sponsors.svg
      - .github/workflows/sponsors.yml
      - sponsorkit.config.*
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npx sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
      - name: Check if sponsors.svg file has changed
        id: check
        run: |
          git diff --exit-code
          echo "changed=$?" >> $GITHUB_OUTPUT
      - name: Commit and push
        if: ${{ steps.check.outputs.changed }}
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add sponsors.svg
          git commit -m "chore: [skip ci] update sponsors"
          git push
